---
title: "R Notebook"
output:
  pdf_document: default
  html_notebook: default
  html_document:
    df_print: paged
  word_document: default
---

```{r}
bike <- read.csv("~/MLDS401_ML1/bike.csv")
View(bike)
```


```{r}
summary(bike)
```

```{r}
bike_crime <- subset(bike, select = c(trips,THEFT,BATTERY,DECEPTIVE_PRACTICE,ASSAULT,BURGLARY,ROBBERY,CRIMINAL_TRESPASS,NARCOTICS,HOMICIDE))

bike_no_crime_pick <- subset(bike, select = c(trips,PARK_AREA_ACRES,CTA_BUS_STATIONS,CTA_TRAIN_STATIONS,BIKE_ROUTES,Limited_Business_License,Retail_Food_Establishment,CAPACITY,PER_CAPITA_INCOME,POPULATION_SQ_MILE,CBD,MINORITY,EDU))
```

```{r}
plot(bike_no_crime_pick)
```

```{r}
plot(bike_crime)
```


```{r}
# only crime
crime = lm(trips ~ THEFT + BATTERY + DECEPTIVE_PRACTICE + ASSAULT + BURGLARY + ROBBERY + CRIMINAL_TRESPASS + NARCOTICS + HOMICIDE, bike)
summary(crime)
```
Significant variables = THEFT, ASSAULT, BURGLARY, ROBBERY, DECEPTIVE_PRACTICE

```{r}
plot(crime)
```

```{r}
vif(crime)
```

```{r}
cor(bike_crime)
```


```{r}
# only !crime
not_crime = lm(trips ~ PARK_AREA_ACRES + CTA_BUS_STATIONS + CTA_TRAIN_STATIONS + BIKE_ROUTES + Limited_Business_License + Retail_Food_Establishment + CAPACITY + PER_CAPITA_INCOME + POPULATION_SQ_MILE + as.factor(CBD) + MINORITY + EDU, bike)
summary(not_crime)
```
Significant variables = PARK_AREA, CTA_BUS, CTA_TRAIN, Business_License, Retail_Food, CAPACITY, MINORTIY

```{r}
plot(not_crime)
```

```{r}
vif(not_crime)
```

```{r}
cor(bike_no_crime_pick)
```


```{r}
# BOTH
both = lm(trips ~ THEFT + ASSAULT + BURGLARY + ROBBERY + DECEPTIVE_PRACTICE + PARK_AREA_ACRES + CTA_BUS_STATIONS + CTA_TRAIN_STATIONS + Limited_Business_License + Retail_Food_Establishment + CAPACITY + MINORITY, bike)
summary(both)
```

```{r}
plot(both)
```

```{r}
vif(both)
```


```{r}
# BOTH
both2 = lm(trips ~ THEFT + ASSAULT + BURGLARY + ROBBERY + DECEPTIVE_PRACTICE + PARK_AREA_ACRES + CTA_BUS_STATIONS + CTA_TRAIN_STATIONS + CAPACITY + MINORITY, bike)
summary(both2)
```

```{r}
plot(both2)
```

```{r}
vif(both2)
```

```{r}

```
